# Generated by Django 3.0.7 on 2020-06-15 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tyre',
            options={'verbose_name': 'Шина', 'verbose_name_plural': 'Шины'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.RemoveField(
            model_name='tyre',
            name='model',
        ),
        migrations.AddField(
            model_name='tyre',
            name='model',
            field=models.ManyToManyField(to='form.Vendor'),
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
