# Generated by Django 3.0.7 on 2020-06-15 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200615_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='vendor',
            field=models.ManyToManyField(to='form.Vendor'),
        ),
        migrations.RemoveField(
            model_name='tyre',
            name='model',
        ),
        migrations.AddField(
            model_name='tyre',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
