# Generated by Django 3.0.7 on 2020-06-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_yml', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tyre',
            options={'verbose_name': 'Шина', 'verbose_name_plural': 'Шины'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='tyre',
            name='model',
            field=models.CharField(max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена $'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor',
            field=models.CharField(max_length=200, verbose_name='Производитель'),
        ),
    ]
