# Generated by Django 3.0.7 on 2020-06-17 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms_yml', '0004_auto_20200617_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming',
            old_name='title',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='incoming',
            name='file',
        ),
        migrations.AddField(
            model_name='incoming',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incoming',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
