# Generated by Django 3.0.7 on 2020-06-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_yml', '0005_auto_20200617_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incoming',
        ),
    ]
